### ISSUE TITLE
Access to the Netphotographics server

### ISSUE THREAD

**Issue by By-oussef** [netPhotoGraphics/Website#19]
Hi, Stephen
 
I am contacting you to help with the Netphotographics project. I would like to have access to the netphotographics server in order to improve the NPG website. Can you give me a filezilla acess as a guest. My project will be to integrate google webmaster tools to track statistics and improve ranking in google. I also want to add google analitycs to follow the user experience.

Very happy to help you.

**Comment by sbillard** [comment]
There is a github repository for the web site which you are welcome to 
make pull requests on.

I should tell you that I am somewhat skeptical that there would be any 
benefit to this effort.  You should be prepared to enumerate the 
benefits of any changes you propose. Since most of our users are forum 
members you can also solicit their opinions there.

At any rate, I will maintain control over any actual changes to the site 
(same as I will maintain control over the netPhotoGraphics software 
itself.)


-Stephen
